name = "sp3fck-ham-tools-api"
main = "src/index.ts"
compatibility_date = "2023-09-01"

[vars]
ENVIRONMENT = "development"

[[d1_databases]]
binding = "DB"
database_name = "ham-tools-db"
database_id = "your-database-id-here"

[build]
command = "npm run build"

[env.production]
name = "sp3fck-ham-tools-api"

[env.production.vars]
ENVIRONMENT = "production"

[[env.production.d1_databases]]
binding = "DB"
database_name = "ham-tools-db-prod"
database_id = "your-prod-database-id-here"
